### ISSUE TITLE
Dependency failed should not be internal error

### ISSUE THREAD

**Issue by bloodearnest** [opensafely-core/job-runner#654] opened 2023-09-13 08:13 UTC
Currently, if a user submits a job request for an action, and that action has a dependendency that failed, we refuse to run the job.

This was a design decision from 3 years ago, and we may be changing it.

But if we dont change it, this shouldn't be an INTERNAL_ERROR

**Comment by madwort** [comment] 2023-09-13 09:06
dupe of #651

**Closed** 2023-09-13 15:54 UTC
