### ISSUE TITLE
🐛 assert_new_jobs_created not working as intended

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/job-runner#517] opened 2022-11-18 17:21 UTC
🧵 https://bennettoxford.slack.com/archives/C03ELD5FEAU/p1668791257640459?thread_ts=1668787886.965909&cid=C03ELD5FEAU

This function should have given the user the error "All requested actions already running" for the job referenced in that thread. This would have helped us identify that there was a problem (🧟 job) more quickly.

Code:
https://github.com/opensafely-core/job-runner/blob/adf78e01faceec8b11e1f4d5d758e204e691b380/jobrunner/create_or_update_jobs.py#L282

**Comment by lucyb** [comment] 2022-11-24 14:22
This also caused an issue again today
https://bennettoxford.slack.com/archives/C0270Q313H7/p1669298318911949?thread_ts=1669298155.368309&cid=C0270Q313H7

**Comment by tomodwyer** [comment] 2023-01-18 10:18
https://bennettoxford.slack.com/archives/C0270Q313H7/p1673887339832989

**Comment by madwort** [comment] 2023-02-10 17:20
see https://github.com/opensafely-core/job-runner/pull/573

**Comment by madwort** [comment] 2023-02-15 11:51
Dave reproducing the issue:

```
# fresh db
rm workdir/db.sqlite
python -m jobrunner.cli.migrate

# add a bunch of jobs
python -m jobrunner.cli.add_job https://github.com/opensafely/comparative-booster run_all

# mark one of those as succeeded
sqlite3 workdir/db.sqlite "update job set state='succeeded' where action='contrasts_combine_A';"

# ask for another job (which will already be pending from the run_all above) to run again
python -m jobrunner.cli.add_job https://github.com/opensafely/comparative-booster contrasts_combine_B
```

**Comment by madwort** [comment] 2023-02-15 11:57
PR merged, will leave this in review a little longer to monitor in Honeycomb whether the number of failures goes down (after, say, a week)

**Comment by madwort** [comment] 2023-02-17 12:53
number of errors has gone up, but they're caused by other failures not by the one fixed in this PR

**Comment by madwort** [comment] 2023-02-22 10:36
no further instances of this issue have been observed since merging the patch, considering this closed.

**Closed by madwort** 2023-02-22 10:36 UTC
